services:
  # MQTT Broker - EMQX
  emqx:
    image: emqx/emqx:5.3.0
    container_name: emqx-broker
    ports:
      - "1883:1883"      # MQTT/TCP
      - "8883:8883"      # MQTT/SSL
      - "8083:8083"      # MQTT/WS
      - "8084:8084"      # MQTT/WSS
      - "18083:18083"    # Dashboard
    volumes:
      - ./emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf:ro
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    restart: unless-stopped
    networks:
      - sensor-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sensor_db
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - sensor-network

volumes:
  postgres_data:
  pgadmin_data:
  emqx_data:
  emqx_log:

networks:
  sensor-network:
    driver: bridge